apiVersion: v1
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/rawabet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"SERVER_PORT":"8081","SPRING_DATASOURCE_URL":"jdbc:mysql://mysql-service:3306/rawabet?useSSL=false\u0026allowPublicKeyRetrieval=true\u0026serverTimezone=UTC","SPRING_JPA_HIBERNATE_DDL_AUTO":"update","SPRING_JPA_SHOW_SQL":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"backend-config","namespace":"default"}}
  creationTimestamp: "2026-05-16T13:40:16Z"
  name: backend-config
  namespace: default
  resourceVersion: "82858"
  uid: 87d826c9-58bd-47ae-bb36-e845040e77f1
